[package]
edition = "2021"
name = "warpgate-db-entities"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
sea-orm = {version = "^0.6", features = ["macros"], default-features = false}
serde = "1.0.136"
uuid = {version = "0.8.2", features = ["v4", "serde"]}
poem-openapi = {version = "1.3.5", features = ["chrono", "uuid"]}
