[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-db-entities"
version = "0.1.0"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
poem-openapi = {version = "^1.3.30", features = ["chrono", "uuid"]}
sea-orm = {version = "^0.7", features = ["macros", "with-chrono", "with-uuid"], default-features = false}
serde = "1.0"
uuid = {version = "1.0", features = ["v4", "serde"]}
