[package]
edition = "2021"
name = "warpgate-db-entities"
version = "0.1.0"
license = "Apache-2.0"

[dependencies]
chrono = "0.4"
sea-orm = {version = "^0.6", features = ["macros"], default-features = false}
serde = "1.0"
uuid = {version = "0.8", features = ["v4", "serde"]}
poem-openapi = {version = "1.3", features = ["chrono", "uuid"]}
