cargo-features = ["workspace-inheritance"]

[package]
name = "warpgate-db-entities"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
poem-openapi.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
