[workspace]
members = [
    "warpgate",
    "warpgate-admin",
    "warpgate-cli",
    "warpgate-common",
    "warpgate-db-migrations",
    "thrussh",
    "thrussh-keys",
    "thrussh-libsodium",
]
default-members = ["warpgate"]

[profile.release]
# strip = true
lto = true
panic = "abort"
