[workspace]
members = [
    "warpgate",
    "warpgate-admin",
    "warpgate-cli",
    "warpgate-common",
    "warpgate-db-migrations",
    "warpgate-db-entities",
    "warpgate-protocol-ssh",
]
default-members = ["warpgate"]

[profile.release]
# strip = true
lto = true
panic = "abort"
