[workspace]
members = [
    "warpgate",
    "warpgate-admin",
    "warpgate-common",
    "thrussh",
    "thrussh-keys",
    "thrussh-libsodium",
]

[profile.release]
# strip = true
lto = true
panic = "abort"
