cargo-features = ["workspace-inheritance"]

[workspace]
default-members = ["warpgate"]
members = [
    "warpgate",
    "warpgate-admin",
    "warpgate-common",
    "warpgate-db-migrations",
    "warpgate-db-entities",
    "warpgate-protocol-http",
    "warpgate-protocol-ssh",
    "warpgate-web",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.3.0"

[workspace.dependencies]
anyhow = { version = "1.0", features = ["backtrace", "std"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
bytes = "1.1"
data-encoding = "2.3"
tracing = "0.1"
lazy_static = "1.4"
dialoguer = "0.10"
futures = "0.3"
poem = { version = "^1.3.30", features = [
    "cookie",
    "session",
    "anyhow",
    "websocket",
    "rustls",
    "websocket",
    "sse",
    "embed",
] }
poem-openapi = { version = "^1.3.30", features = [
    "swagger-ui",
    "chrono",
    "uuid",
    "static-files",
] }
russh = { version = "0.34.0-beta.5", features = ["openssl"] }
russh-keys = { version = "0.22.0-beta.3", features = ["openssl"] }
rust-embed = "6.3"
time = "0.3"
tokio = { version = "1.19", features = ["tracing", "signal", "macros"] }
sea-orm = { version = "^0.8", features = [
    "sqlx-sqlite",
    "runtime-tokio-native-tls",
    "macros",
    "with-chrono",
    "with-uuid",
    "with-json",
], default-features = false }
serde = "1.0"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4", "serde"] }
serde_json = "1.0"

[profile.release]
lto = true
panic = "abort"
strip = "debuginfo"
