targets:
- name: qa233
  host: 192.168.78.233
- name: qa221
  host: 192.168.78.221
- name: bad
  host: 192.168.1.1

users:
- username: user
  auth:
    type: publickey
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINtbl2EekdtAGGuilLQJebKP3pSOlI4KNVCnXPThbD4I
