targets:
- name: qa233
  host: 192.168.78.233
- name: qa221
  host: 192.168.78.221
- name: bad
  host: 192.168.1.1

users:
- username: user
  credentials:
  - type: publickey
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINtbl2EekdtAGGuilLQJebKP3pSOlI4KNVCnXPThbD4I
  - type: password
    password: '$argon2id$v=19$m=4096,t=3,p=1$hb5PNgUGKrpb/+lfuaJzhA$FjBFacz27XoPgToFywtYO+lGp8JBQm4lJGAr/lHj5Yg'

recordings_path: data/recordings
database_url: sqlite:data/db.sqlite3?mode=rwc
