targets:
- name: qa233
  roles: [qa, admin]
  ssh:
    host: 192.168.78.233

- name: qa221
  roles: [qa, admin]
  ssh:
    host: 192.168.76.221

- name: ai
  roles: [qa, admin]
  ssh:
    username: syslink
    host: 192.168.72.29

- name: localhost
  roles: [admin]
  ssh:
    host: localhost

users:
- username: user
  credentials:
  - type: publickey
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINtbl2EekdtAGGuilLQJebKP3pSOlI4KNVCnXPThbD4I
  - type: password
    password: '$argon2id$v=19$m=4096,t=3,p=1$hb5PNgUGKrpb/+lfuaJzhA$FjBFacz27XoPgToFywtYO+lGp8JBQm4lJGAr/lHj5Yg'
  # require: [publickey, password]
  roles: [qa]

- username: admin
  credentials:
  - type: publickey
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINtbl2EekdtAGGuilLQJebKP3pSOlI4KNVCnXPThbD4I
  roles: [admin]

roles:
- name: qa
- name: admin

recordings:
  enable: true
  path: data/recordings

database_url: sqlite:data/db

ssh:
  listen: 0.0.0.0:2222

web_admin:
  enable: true
