[package]
edition = "2021"
name = "warpgate-admin"
version = "0.1.0"

[dependencies]
anyhow = "1.0.53"
chrono = "0.4.19" # Date and time library for Rust
futures = "0.3.19"
okapi = {version = "0.5.0-alpha-1", features = ["derive_json_schema"]}
rocket = "0.5.0-rc.1"
rocket_okapi = {version = "0.8.0-rc.1", features = ["swagger"]}
schemars = {version = "0.8.8", features = ["uuid"]}
sea-orm = {version = "^0.6", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"], default-features = false}
serde = "1.0.136"
serde_json = "1.0.79"
tokio = {version = "1.16.1", features = ["tracing"]}
tracing = "0.1.30"
uuid = {version = "0.8.2", features = ["v4", "serde"]}
warpgate-common = {version = "*", path = "../warpgate-common"}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
