[package]
edition = "2021"
name = "warpgate-admin"
version = "0.1.0"

[dependencies]
anyhow = "1.0.53"
futures = "0.3.19"
okapi = {version = "0.5.0-alpha-1", features = ["derive_json_schema"]}
rocket = "0.5.0-rc.1"
rocket_okapi = {version = "0.8.0-rc.1", features = ["swagger"]}
schemars = {version = "0.8.8", features = ["uuid"]}
serde = "1.0.136"
serde_json = "1.0.79"
tokio = {version = "1.16.1", features = ["tracing"]}
tracing = "0.1.30"
warpgate-common = {version = "*", path = "../warpgate-common"}
uuid = {version = "0.8.2", features = ["v4", "serde"]}
