cargo-features = ["workspace-inheritance"]

[package]
name = "warpgate-admin"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
futures.workspace = true
hex = "0.4"
mime_guess = { version = "2.0", default_features = false }
poem.workspace = true
poem-openapi.workspace = true
russh-keys.workspace = true
rust-embed.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
warpgate-protocol-ssh = { version = "*", path = "../warpgate-protocol-ssh" }
warpgate-web = { version = "*", path = "../warpgate-web" }
