[package]
edition = "2021"
name = "warpgate-admin"
version = "0.1.0"
license = "Apache-2.0"

[dependencies]
anyhow = {version = "1.0", features = ["std"]}
async-trait = "0.1"
chrono = "0.4"
futures = "0.3"
poem = {version = "1.3", features = ["cookie", "static-files", "websocket", "anyhow"]}
sea-orm = {version = "^0.6", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"], default-features = false}
serde = "1.0"
serde_json = "1.0"
tokio = {version = "1.17", features = ["tracing"]}
tracing = "0.1"
uuid = {version = "0.8", features = ["v4", "serde"]}
warpgate-common = {version = "*", path = "../warpgate-common"}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
poem-openapi = {version="1.3", features=["swagger-ui", "chrono","uuid","static-files"]}
