[package]
name = "warpgate-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.16.1", features = ["tracing"]}
tracing = "0.1.30"
anyhow = "1.0.53"
warpgate-common = {version = "*", path = "../warpgate-common"}
serde = "1.0.136"
serde_json = "1.0.79"
futures = "0.3.19"
rocket = "0.5.0-rc.1"
rocket_okapi = { version = "0.8.0-rc.1", features = ["swagger"] }
okapi = { version = "0.5.0-alpha-1", features = ["derive_json_schema"] }
schemars = "0.8"
