[package]
name = "warpgate-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.16.1", features = ["tracing"]}
tracing = "0.1.30"
anyhow = "1.0.53"
warp = "0.3"
warpgate-common = {version = "*", path = "../warpgate-common"}
serde = "1.0.136"
serde_json = "1.0.79"
futures = "0.3.19"
