[package]
edition = "2021"
name = "warpgate-admin"
version = "0.1.0"

[dependencies]
anyhow = {version = "1.0.53", features = ["std"]}
chrono = "0.4.19" # Date and time library for Rust
futures = "0.3.19"
poem = {version = "1.3.5", features = ["cookie", "static-files", "websocket", "anyhow"]}
sea-orm = {version = "^0.6", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"], default-features = false}
serde = "1.0.136"
serde_json = "1.0.79"
tokio = {version = "1.16.1", features = ["tracing"]}
tracing = "0.1.30"
uuid = {version = "0.8.2", features = ["v4", "serde"]}
warpgate-common = {version = "*", path = "../warpgate-common"}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
poem-openapi = {version="1.3.5", features=["swagger-ui", "chrono","uuid","static-files"]}
