[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-protocol-http"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
poem = {version = "^1.3.30", features = ["cookie", "session", "anyhow", "rustls", "websocket", "sse", "embed"]}
warpgate-common = {version = "*", path = "../warpgate-common"}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
tokio = {version = "1.18", features = ["tracing", "signal"]}
tracing = "0.1"
data-encoding = "2.3"
reqwest = {version="0.11", features=["rustls-tls-native-roots", "stream"]}
http = "0.2"
