[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-protocol-http"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
data-encoding = "2.3"
http = "0.2"
poem = {version = "^1.3.30", features = ["cookie", "session", "anyhow", "rustls", "websocket", "sse", "embed"]}
reqwest = {version = "0.11", features = ["rustls-tls-native-roots", "stream"]}
tokio = {version = "1.18", features = ["tracing", "signal"]}
tokio-tungstenite = {version = "0.17", features = ["rustls-tls-native-roots"]}
tracing = "0.1"
warpgate-common = {version = "*", path = "../warpgate-common"}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
lazy_static = "1.4"
futures = "0.3"
delegate = "0.6"
