cargo-features = ["workspace-inheritance"]

[package]
name = "warpgate-protocol-http"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
cookie = "0.16"
data-encoding.workspace = true
delegate = "0.6"
futures.workspace = true
http = "0.2"
lazy_static.workspace = true
poem.workspace = true
poem-openapi.workspace = true
reqwest = {version = "0.11", features = ["rustls-tls-native-roots", "stream"]}
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-tungstenite = {version = "0.17", features = ["rustls-tls-native-roots"]}
tracing.workspace = true
warpgate-admin = {version = "*", path = "../warpgate-admin"}
warpgate-common = {version = "*", path = "../warpgate-common"}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
warpgate-web = {version = "*", path = "../warpgate-web"}
percent-encoding = "2.1"
uuid.workspace = true
