cargo-features = ["workspace-inheritance"]

[package]
name = "warpgate-web"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
