[package]
edition = "2021"
name = "warpgate-common"
version = "0.1.0"

[dependencies]
anyhow = "1.0.53"
bytes = "1.1.0"
chrono = "0.4.19"
data-encoding = "2.3"
poem-openapi = {version = "1.3.5", features = ["swagger-ui", "chrono", "uuid", "static-files"]}
sea-orm = {version = "^0.6", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"], default-features = false}
serde = "1.0.136"
serde_json = "1.0.79"
serde_yaml = "0.8"
tokio = {version = "1.16.1", features = ["tracing"]}
tracing = "0.1.30"
uuid = {version = "0.8.2", features = ["v4", "serde"]}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
warpgate-db-migrations = {version = "*", path = "../warpgate-db-migrations"}
packet = "0.1.4"
rand = "0.8.5"
