cargo-features = ["workspace-inheritance"]

[package]
name = "warpgate-common"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
argon2 = "0.4"
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
data-encoding.workspace = true
humantime-serde = "1.1"
lazy_static.workspace = true
once_cell = "1.10"
packet = "0.1"
password-hash = "0.4"
poem-openapi.workspace = true
rand = "0.8"
rand_chacha = "0.3"
rand_core = {version = "0.6", features = ["std"]}
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
totp-rs = {version = "2.0", features = ["otpauth"]}
tracing.workspace = true
tracing-core = "0.1"
tracing-subscriber = "0.3"
url = "2.2"
uuid.workspace = true
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
warpgate-db-migrations = {version = "*", path = "../warpgate-db-migrations"}
