[package]
edition = "2021"
name = "warpgate-common"
version = "0.1.0"

[dependencies]
anyhow = "1.0.53"
bytes = "1.1.0"
chrono = "0.4.19" # Date and time library for Rust
data-encoding = "2.3"
warpgate-db-migrations = {version = "*", path = "../warpgate-db-migrations"}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
rocket = "0.5.0-rc.1"
rocket_okapi = {version = "0.8.0-rc.1", features = ["swagger"]}
schemars = {version = "0.8.8", features = ["uuid", "chrono"]}
sea-orm = {version = "^0.6", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"], default-features = false}
serde = "1.0.136"
serde_yaml = "0.8"
tokio = {version = "1.16.1", features = ["tracing"]}
tracing = "0.1.30"
uuid = {version = "0.8.2", features = ["v4", "serde"]}
serde_json = "1.0.79"
