[package]
name = "warpgate-protocol-ssh"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
bytes = "1.1"
futures = "0.3"
russh = {version = "0.34.0-beta.1", features = ["openssl"]}
russh-keys = {version = "0.22.0-beta.1", features = ["openssl"]}
time = "0.3"
tokio = {version = "1.17", features = ["tracing", "signal"]}
tracing = "0.1"
sea-orm = {version = "^0.6", features = ["runtime-tokio-native-tls"], default-features = false}
warpgate-common = {version = "*", path = "../warpgate-common"}
async-trait = "0.1"
uuid = {version = "0.8", features = ["v4"]}
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
