[package]
name = "warpgate-protocol-ssh"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.53"
bytes = "1.1.0"
futures = "0.3.19"
thrussh = {version = "0.33.5", features = ["openssl"], path = "../thrussh"}
thrussh-keys = {version = "0.21.0", features = ["openssl"], path = "../thrussh-keys"}
time = "0.3.7"
tokio = {version = "1.17.0", features = ["tracing", "signal"]}
tracing = "0.1.30"
warpgate-common = {version = "*", path = "../warpgate-common"}
async-trait = "0.1.52"
