cargo-features = ["workspace-inheritance"]

[package]
name = "warpgate-protocol-ssh"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
ansi_term = "0.12"
anyhow.workspace = true
async-trait.workspace = true
bimap = "0.6"
bytes.workspace = true
dialoguer.workspace = true
futures.workspace = true
russh.workspace = true
russh-keys.workspace = true
sea-orm.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
warpgate-common = { version = "*", path = "../warpgate-common" }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities" }
