cargo-features = ["workspace-inheritance"]

[package]
name = "warpgate-db-migrations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]

[dependencies]
async-std = "^1.11"
chrono.workspace = true
sea-orm.workspace = true
sea-orm-migration = {version = "^0.8", default-features = false}
uuid.workspace = true
