[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-db-migrations"
publish = false
version = "0.1.0"

[lib]

[dependencies]
chrono = "0.4"
sea-orm = {version = "^0.7", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"], default-features = false}
sea-schema = {version = "0.7", default-features = false, features = ["migration", "debug-print"]}
uuid = {version = "1.0", features = ["v4", "serde"]}
