[package]
name = "warpgate-db-migrations"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]

[dependencies]
sea-schema = { version = "0.5", default-features = false, features = [ "migration", "debug-print" ] }
uuid = {version = "0.8", features = ["v4", "serde"]}
chrono = "0.4"
sea-orm = {version = "^0.6", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"], default-features = false}
