[package]
name = "warpgate-db-migrations"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
sea-schema = { version = "0.5.0", default-features = false, features = [ "migration", "debug-print" ] }
warpgate-db-entities = {version = "*", path = "../warpgate-db-entities"}
uuid = {version = "0.8.2", features = ["v4", "serde"]}
chrono = "0.4.19"
sea-orm = {version = "^0.6", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"], default-features = false}
