[package]
name = "warpgate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thrussh = { version="0.33.5", features=["openssl"], path="../thrussh" }
thrussh-keys = { version="0.21.0", features=["openssl"], path="../thrussh-keys" }
futures = "0.3.19"
tokio = "1.16.1"
anyhow = "1.0.53"
bytes = "1.1.0"
dhat = "0.3.0"
env_logger = "0.9.0"
log = "0.4.14"

[features]
dhat-heap = []    # if you are doing heap profiling
dhat-ad-hoc = []  # if you are doing ad hoc profiling
