[package]
edition = "2021"
name = "warpgate-cli"
version = "0.1.0"

[dependencies]
anyhow = "1.0.53"
clap = {version = "3.1.6", features = ["derive"]}
warpgate-common = {version = "*", path = "../warpgate-common"}
dialoguer = "0.10.0"
